### Aerospace startup settings
start-at-login = true
after-login-command = []
after-startup-command = []
key-mapping.preset = 'qwerty'

### Normalizations. See: https://nikitabobko.github.io/AeroSpace/guide#normalization
enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

### Layouts settings
accordion-padding = 50
default-root-container-layout = 'tiles'
default-root-container-orientation = 'auto'

# Mouse follows focus when focused monitor changes
on-focused-monitor-changed = ['move-mouse monitor-lazy-center']

[gaps]
inner.horizontal = 12
inner.vertical =   12
outer.left =       8
outer.bottom =     8
outer.top =        8
outer.right =      8

[mode.main.binding]

cmd-h = [] # Disable "hide application"
cmd-alt-h = [] # Disable "hide others"

# exec commands
alt-shift-ctrl-cmd-enter = 'exec-and-forget kitty --single-instance -d ~'

alt-shift-ctrl-c = 'reload-config' # aerospace config
alt-shift-ctrl-b = 'exec-and-forget brew services restart felixkratz/formulae/borders' # jankyborders

# layouts
alt-shift-ctrl-cmd-slash = 'layout tiles horizontal vertical'
alt-shift-ctrl-cmd-comma = 'layout accordion horizontal vertical'
alt-shift-ctrl-cmd-f = 'layout floating tiling'

# focus
alt-h = 'focus left'
alt-j = 'focus down'
alt-k = 'focus up'
alt-l = 'focus right'
alt-f = 'fullscreen'

# move
alt-shift-h = 'move left'
alt-shift-j = 'move down'
alt-shift-k = 'move up'
alt-shift-l = 'move right'

# warp (Yabai Equivalent?)
alt-shift-ctrl-h = 'join-with left'
alt-shift-ctrl-j = 'join-with down'
alt-shift-ctrl-k = 'join-with up'
alt-shift-ctrl-l = 'join-with right'

# resize
alt-shift-ctrl-cmd-minus = 'resize smart -150'
alt-shift-ctrl-cmd-equal = 'resize smart +150'
alt-shift-ctrl-cmd-b = 'balance-sizes'

# alternate workspace
alt-1 = 'workspace 1'
alt-2 = 'workspace 2'
alt-3 = 'workspace 3'
alt-4 = 'workspace 4'
alt-5 = 'workspace 5'
alt-6 = 'workspace 6'
alt-7 = 'workspace 7'
alt-8 = 'workspace 8'
alt-9 = 'workspace 9'

# move-node-to-workspace
alt-shift-1 = ['move-node-to-workspace 1', 'workspace 1']
alt-shift-2 = ['move-node-to-workspace 2', 'workspace 2']
alt-shift-3 = ['move-node-to-workspace 3', 'workspace 3']
alt-shift-4 = ['move-node-to-workspace 4', 'workspace 4']
alt-shift-5 = ['move-node-to-workspace 5', 'workspace 5']
alt-shift-6 = ['move-node-to-workspace 6', 'workspace 6']
alt-shift-7 = ['move-node-to-workspace 7', 'workspace 7']
alt-shift-8 = ['move-node-to-workspace 8', 'workspace 8']
alt-shift-9 = ['move-node-to-workspace 9', 'workspace 9']

# workspace-back-and-forth
alt-tab = 'workspace-back-and-forth'
# move-workspace-to-monitor
alt-shift-tab = 'move-workspace-to-monitor --wrap-around next'

# Modes
alt-shift-r = 'mode resize'

### Resize binding mode declaration.
[mode.resize.binding]
esc = 'mode main'
b = 'balance-sizes'
minus = 'resize smart -50'
equal = 'resize smart +50'
f = 'flatten-workspace-tree' # reset layout

### Monitor assignment
# This seems like it needs to after be workspace bindings
[workspace-to-monitor-force-assignment]
1 = 1
2 = 1
3 = 1
4 = 2
5 = 2
6 = 2
7 = 3
8 = 3
9 = 3

[[on-window-detected]]
if.app-id = 'com.1password.1password'
run = 'layout floating'
