### Aerospace startup settings
start-at-login = true
after-login-command = []
after-startup-command = []
key-mapping.preset = 'qwerty'

### Normalizations. See: https://nikitabobko.github.io/AeroSpace/guide#normalization
enable-normalization-flatten-containers = false
enable-normalization-opposite-orientation-for-nested-containers = false

### Layouts settings
accordion-padding = 50
default-root-container-layout = 'tiles'
default-root-container-orientation = 'horizontal'

# Mouse follows focus when focused monitor changes
on-focused-monitor-changed = ['move-mouse monitor-lazy-center']

[gaps]
inner.horizontal = 12
inner.vertical = 12
outer.left = 8
outer.bottom = 8
outer.top = 8
outer.right = 8

#[key-mapping.key-notation-to-key-code]
#hyper = 'ctrl-alt-shift-cmd'
[mode.main.binding]

# Modes
ctrl-alt-shift-cmd-w = 'mode warp'
ctrl-alt-shift-cmd-r = 'mode resize'
ctrl-alt-shift-cmd-space = 'mode alt'

cmd-h = []     # Disable "hide application"
cmd-alt-h = [] # Disable "hide others"

# exec commands
ctrl-alt-shift-cmd-enter = [
    'exec-and-forget kitty --single-instance -d ~',
    'split horizontal',
]
ctrl-alt-shift-cmd-backspace = [
    'exec-and-forget kitty --single-instance -d ~',
    'split opposite',
]

ctrl-alt-shift-cmd-c = 'reload-config'                                                 # aerospace config
alt-shift-ctrl-b = 'exec-and-forget brew services restart felixkratz/formulae/borders' # jankyborders

# layouts
ctrl-alt-shift-cmd-slash = 'layout h_tiles v_tiles'
ctrl-alt-shift-cmd-comma = 'layout h_accordion v_accordion'
ctrl-alt-shift-cmd-f = 'layout floating tiling'

# focus
alt-h = 'focus left'
alt-j = 'focus down'
alt-k = 'focus up'
alt-l = 'focus right'
alt-f = 'fullscreen'

# move
alt-shift-h = 'move left'
alt-shift-j = 'move down'
alt-shift-k = 'move up'
alt-shift-l = 'move right'

# warp (Yabai Equivalent?)
ctrl-alt-shift-cmd-h = 'split horizontal'
ctrl-alt-shift-cmd-v = 'split vertical'
#alt-shift-ctrl-k = 'join-with up'
#alt-shift-ctrl-l = 'join-with right'

# resize
ctrl-alt-shift-cmd-minus = 'resize smart -150'
ctrl-alt-shift-cmd-equal = 'resize smart +150'
ctrl-alt-shift-cmd-b = 'balance-sizes'

# alternate workspace
alt-1 = 'workspace 1'
alt-2 = 'workspace 2'
alt-3 = 'workspace 3'
alt-4 = 'workspace 4'
alt-5 = 'workspace 5'
alt-6 = 'workspace 6'
alt-7 = 'workspace 7'
alt-8 = 'workspace 8'
alt-9 = 'workspace 9'

# move-node-to-workspace
alt-shift-1 = ['move-node-to-workspace 1', 'workspace 1']
alt-shift-2 = ['move-node-to-workspace 2', 'workspace 2']
alt-shift-3 = ['move-node-to-workspace 3', 'workspace 3']
alt-shift-4 = ['move-node-to-workspace 4', 'workspace 4']
alt-shift-5 = ['move-node-to-workspace 5', 'workspace 5']
alt-shift-6 = ['move-node-to-workspace 6', 'workspace 6']
alt-shift-7 = ['move-node-to-workspace 7', 'workspace 7']
alt-shift-8 = ['move-node-to-workspace 8', 'workspace 8']
alt-shift-9 = ['move-node-to-workspace 9', 'workspace 9']

# workspace-back-and-forth
alt-tab = 'workspace-back-and-forth'
alt-shift-right = 'move-node-to-monitor prev'
alt-shift-left = 'move-node-to-monitor next'

### Alt Mode
[mode.alt.binding]
esc = ['mode main']

# layouts
slash = ['layout tiles horizontal vertical']
comma = ['layout accordion horizontal vertical']
cmd-f = ['layout floating tiling', 'mode main']

# focus window
h = ['focus --boundaries-action stop left', 'move-mouse window-force-center']
j = ['focus --boundaries-action stop down', 'move-mouse window-force-center']
k = ['focus --boundaries-action stop up', 'move-mouse window-force-center']
l = ['focus --boundaries-action stop right', 'move-mouse window-force-center']

# move window
shift-h = 'move left'
shift-j = 'move down'
shift-k = 'move up'
shift-l = 'move right'

# warp (Yabai Equivalent?)
shift-ctrl-h = 'join-with left'
shift-ctrl-j = 'join-with down'
shift-ctrl-k = 'join-with up'
shift-ctrl-l = 'join-with right'

# resize
minus = 'resize smart -149'
equal = 'resize smart +150'
b = 'balance-sizes'

### Resize Mode
[mode.resize.binding]
esc = 'mode main'
b = 'balance-sizes'
minus = 'resize smart -50'
equal = 'resize smart +50'
f = 'flatten-workspace-tree' # reset layout

### Warp Mode
[mode.warp.binding]
h = 'join-with left'
j = 'join-with down'
k = 'join-with up'
l = 'join-with right'
esc = 'mode main'

### Monitor assignment
# This seems like it needs to after be workspace bindings
[workspace-to-monitor-force-assignment]
1 = 1
2 = 1
3 = 1
4 = 2
5 = 2
6 = 2
7 = 3
8 = 3
9 = 3

[[on-window-detected]]
if.app-id = 'com.1password.1password'
run = 'layout floating'
