# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

#format = '$all$character'
# ➜ [$symbol]($style)

[username]
format = '[$user]($style) '
disabled = false
show_always = true

# [username]
# format = '\[[$user]($style)\]'

[shell]
zsh_indicator = 'zsh'
disabled = true

[battery]
disabled = true

# w/o version
[aws]
symbol = "  "
format = '➜ [$symbol]($style)'

[buf]
symbol = " "
format = '➜ [$symbol]($style)'

[c]
symbol = " "
format = '➜ [$symbol]($style)'

[conda]
symbol = " "
format = '➜ [$symbol]($style)'

[dart]
symbol = " "
format = '➜ [$symbol]($style)'

[directory]
read_only = " 󰌾"

[docker_context]
symbol = " "
format = '➜ [$symbol]($style)'

[elixir]
symbol = " "
format = '➜ [$symbol]($style)'

[elm]
symbol = " "
format = '➜ [$symbol]($style)'

[fossil_branch]
symbol = " "
format = '➜ [$symbol]($style)'

[git_branch]
symbol = " "
format = '➜ [$symbol]($style)'

[golang]
symbol = " "
format = '➜ [$symbol]($style)'

[guix_shell]
symbol = " "
format = '➜ [$symbol]($style)'

[haskell]
symbol = " "
format = '➜ [$symbol]($style)'

[haxe]
symbol = " "
format = '➜ [$symbol]($style)'

[hg_branch]
symbol = " "
format = '➜ [$symbol]($style)'

[hostname]
ssh_symbol = " "
format = '➜ [$symbol]($style)'

[java]
symbol = " "
format = '➜ [$symbol]($style)'

[julia]
symbol = " "
format = '➜ [$symbol]($style)'

[lua]
symbol = " "
format = '➜ [$symbol]($style)'

[memory_usage]
symbol = "󰍛 "
format = '➜ [$symbol]($style)'

[meson]
symbol = "󰔷 "
format = '➜ [$symbol]($style)'

[nim]
symbol = "󰆥 "
format = '➜ [$symbol]($style)'

[nix_shell]
symbol = " "
format = '➜ [$symbol]($style)'

[nodejs]
symbol = " "
format = '➜ [$symbol]($style)'

[os.symbols]
Macos = " "

[package]
symbol = "󰏗 "
format = '➜ [$symbol]($style)'

[pijul_channel]
symbol = " "
format = '➜ [$symbol]($style)'

[python]
symbol = " "
format = '➜ [$symbol]($style)'

[rlang]
symbol = "󰟔 "
format = '➜ [$symbol]($style)'

[ruby]
symbol = " "
format = '➜ [$symbol]($style)'

[rust]
symbol = " "
format = '➜ [$symbol]($style)'

[scala]
symbol = " "
format = '➜ [$symbol]($style)'
