return {
	-- tokyonight night
	-- { label = "bg", color = "#1a1b26" },
	{ label = "bg_dark", color = "#16161e" },
	{ label = "bg_float", color = "#1e2030" },
	{ label = "bg_highlight", color = "#2f334d" },
	{ label = "terminal_black", color = "#444a73" },
	-- { label = "fg", color = "#c8d3f5" },
	{ label = "fg_dark", color = "#828bb8" },
	{ label = "fg_gutter", color = "#3b4261" },
	{ label = "dark3", color = "#545c7e" },
	{ label = "comment", color = "#7a88cf" },
	{ label = "blue", color = "#82aaff" },
	{ label = "cyan", color = "#86e1fc" },
	{ label = "blue1", color = "#65bcff" },
	{ label = "blue2", color = "#0db9d7" },
	{ label = "blue5", color = "#89ddff" },
	{ label = "blue6", color = "#b4f9f8" },
	{ label = "magenta", color = "#c099ff" },
	{ label = "magenta2", color = "#ff007c" },
	{ label = "purple", color = "#fca7ea" },
	{ label = "orange", color = "#ff966c" },
	{ label = "yellow", color = "#ffc777" },
	{ label = "green", color = "#c3e88d" },
	{ label = "green1", color = "#4fd6be" },
	{ label = "green2", color = "#41a6b5" },
	{ label = "teal", color = "#4fd6be" },
	{ label = "red", color = "#ff757f" },
	{ label = "red1", color = "#c53b53" },
}
