[colors.bright]
black = "#1e2737"
blue = "#6db3ce"
cyan = "#7eddde"
green = "#8fc8bb"
magenta = "#ad82cb"
red = "#e78482"
white = "#f5f5f5"
yellow = "#ffd484"

[colors.hints.end]
background = "#1e2737"
foreground = "#fff9ee"

[colors.hints.start]
background = "#fff9ee"
foreground = "#1e2737"

[colors.normal]
black = "#1e2737"
blue = "#6db3ce"
cyan = "#7eddde"
green = "#8fc8bb"
magenta = "#ad82cb"
red = "#e78482"
white = "#f5f5f5"
yellow = "#ffd484"

[colors.primary]
background = "#1e2737"
foreground = "#fff9ee"

[colors.footer_bar]
background = "#ffd484"
foreground = "#1e2737"

[colors.search.focused_match]
background = "#7eddde"
foreground = "#1e2737"

[colors.search.matches]
background = "#fff9ee"
foreground = "#1e2737"
