#!/bin/bash

## JankyBorders
# https://github.com/FelixKratz/JankyBorders

# map color names
get_hex() {
	case $1 in
    # catppuccin theme
    catp_red) echo "f38ba8" ;;
	catp_blue) echo "89b4fa" ;;
    catp_green) echo "a6e3a1" ;;
    catp_yellow) echo "f9e2af" ;;
    catp_peach) echo "fab387" ;;
	catp_lavender) echo "b4befe" ;;
    catp_mantle) echo "181825" ;;
    catp_crust) echo "11111b" ;;

	# rose-pine theme
	love) echo "EB6F92" ;;
	gold) echo "F6C177" ;;
	rose) echo "EBBCBA" ;;
	pine) echo "31748F" ;;
	foam) echo "56949F" ;;
	iris) echo "C4A7E7" ;;
	base) echo "191724" ;;

    # cyberdream
    cblue) echo "5ea1ff" ;;
    cgreen) echo "5eff6c" ;;
    ccyan) echo "5ef1ff" ;;
    cred) echo "ff6e5e" ;;
    cyellow) echo "f1ff5e" ;;
    cmagenta) echo "ff5ef1" ;;
    cpink) echo "ff5ea0" ;;
    corange) echo "ffbd5e" ;;
    cpurple) echo "bd5eff" ;;
    cbg) echo "16181a" ;;

	# dracula theme
	dcyan) echo "8BE9FD" ;;
	dgreen) echo "50FA7B" ;;
	dorange) echo "FFB86C" ;;
	dpink) echo "FF79C6" ;;
	dpurple) echo "BD93F9" ;;
	dred) echo "FF5555" ;;
	dyellow) echo "F1FA8C" ;;
	dcurrent) echo "44475A" ;;

	# tokyonight theme
	tkdblue) echo "82AAFF" ;;
	tklblue) echo "7DD0FF" ;;
	tkpurple) echo "BC9BF7" ;;
	tkyellow) echo "E1AF68" ;;
	tkgreen) echo "9FCE6A" ;;
	tkred) echo "F7768E" ;;

	# default color
	*) echo "ffffff" ;;
	esac
}

# set color
act_color="catp_yellow"
ina_color="catp_crust"
# bg_color="catp_crust"

OPTIONS=(
	hidpi=on
	width=4.0
	style=round
	blur_radius=80.0
	# background_color="0xff$(get_hex $bg_color)"
	active_color="0xff$(get_hex $act_color)"
	inactive_color="0xff$(get_hex $ina_color)"
)

borders "${OPTIONS[@]}"
