#!/bin/bash

## JankyBorders
# https://github.com/FelixKratz/JankyBorders

# map color names
get_hex() {
	case $1 in
	# rose-pine theme
	love) echo "EB6F92" ;;
	gold) echo "F6C177" ;;
	rose) echo "EBBCBA" ;;
	pine) echo "31748F" ;;
	foam) echo "56949F" ;;
	iris) echo "C4A7E7" ;;
	base) echo "191724" ;;

	# dracula theme
	cyan) echo "8BE9FD" ;;
	green) echo "50FA7B" ;;
	orange) echo "FFB86C" ;;
	pink) echo "FF79C6" ;;
	purple) echo "BD93F9" ;;
	red) echo "FF5555" ;;
	yellow) echo "F1FA8C" ;;
	current) echo "44475A" ;;

	# tokyonight theme
	tkdblue) echo "82AAFF" ;;
	tklblue) echo "7DD0FF" ;;
	tkpurple) echo "BC9BF7" ;;
	tkyellow) echo "E1AF68" ;;
	tkgreen) echo "9FCE6A" ;;
	tkred) echo "F7768E" ;;

	# default color
	*) echo "ffffff" ;;
	esac
}

# set color
act_color="tkpurple"
ina_color="base"
bg_color="love"

OPTIONS=(
	hidpi=on
	width=5.0
	style=round
	# blur_radius=80.0
	# background_color="0xff$(get_hex $bg_color)"
	active_color="0xff$(get_hex $act_color)"
	inactive_color="0xff$(get_hex $ina_color)"
)

borders "${OPTIONS[@]}"
