return {
	-- catppuccin mocha
	{ label = "rosewater", color = "#f5e0dc" },
	{ label = "flamingo", color = "#f2cdcd" },
	{ label = "pink", color = "#f5c2e7" },
	{ label = "mauve", color = "#cba6f7" },
	{ label = "red", color = "#f38ba8" },
	{ label = "maroon", color = "#eba0ac" },
	{ label = "peach", color = "#fab387" },
	{ label = "yellow", color = "#f9e2af" },
	{ label = "green", color = "#a6e3a1" },
	{ label = "teal", color = "#94e2d5" },
	{ label = "sky", color = "#89dceb" },
	{ label = "sapphire", color = "#74c7ec" },
	{ label = "blue", color = "#89b4fa" },
	{ label = "lavender", color = "#b4befe" },
	{ label = "text", color = "#cdd6f4" },
	{ label = "subtext1", color = "#bac2de" },
	{ label = "subtext0", color = "#a6adc8" },
	{ label = "overlay2", color = "#9399b2" },
	{ label = "overlay1", color = "#7f849c" },
	{ label = "overlay0", color = "#6c7086" },
	{ label = "surface2", color = "#585b70" },
	{ label = "surface1", color = "#45475a" },
	{ label = "surface0", color = "#313244" },
	{ label = "base", color = "#1e1e2e" },
	{ label = "mantle", color = "#181825" },
	{ label = "crust", color = "#11111b" },
}
