return {
	yabai = {
		grid = "􀧍",
		float = "􀢌",
		stack = "􀏭",
		parent_zoom = "􀥃",
		split_vertical = "􀘜",
		fullscreen_zoom = "􀂓",
		split_horizontal = "􀧋",
	},
	general = {
		cmd = "󰘳",
		lock = "󰌾",
		app = "􀏜", -- fallback app
	},
	browsers = {
		web = "󰇧",
		safari = "",
		firefox = "󰈹",
		google_chrome = "",
		firefox_dev = "",
	},
	terminal = {
		default = "􀩼",
		kitty = "􀪏",
		ghostty = "",
	},
	dev = {
		default = "",
		code = "",
		sublime_text = "",
	},
	ai = {
		default = "",
	},
	mail = {
		default = "􀍖",
		mimestream = "",
	},
	music = {
		default = "",
		spotify = "",
		itunes = "",
	},
	chat = {
		default = "􀼂",
		steam = "󰓓",
		slack = "",
		twitch = "",
		discord = "",
		whatsapp = "",
		telegram = "",
	},
	macos = {
		tv = "􀡴",
		cog = "􀍟",
		siri = "􂮢",
		maps = "",
		news = "􀥅",
		home = "􀠀",
		clock = "󰥔",
		books = "",
		notes = "󱞎",
		pages = "",
		stocks = "􀑁",
		finder = "󰀶",
		photos = "",
		preview = "󰋲",
		weather = "󰖕",
		find_my = "󰍒",
		numbers = "󱕍",
		keynote = "󰐩",
		facetime = "􀱱",
		freeform = "􀤑",
		podcasts = "󰦔",
		contacts = "󰛋",
		calendar = "􀉉",
		passwords = "􀞚",
		reminders = "󱃔",
		app_store = "",
		font_book = "",
		dictionary = "󱁯",
		sf_symbols = "􂮱",
		calculator = "",
		voice_memos = "󰍬",
		photo_booth = "󰄀",
		disk_utility = "􀯰",
		keychain_access = "󱕴",
		image_playground = "􂮖",
		activity_monitor = "󰺓",
	},
	design = {
		sketch = "",
		photoshop = "",
		aftereffects = "󱁑",
		indesign = "󰴑",
		illustrator = "",
		figma = "",
	},
	other = {
		glm = "󰓃",
		vpn = "󰦝",
		git = "󰊢",
		list = "󱃔",
		play = "󱉺",
		cast = "󱒃",
		table = "󰓫",
		kicad = "",
		cloud = "󰅧",
		popcorn = "􁐈",
		package = "󰏓",
		rustdesk = "󰞯",
		download = "󱑢",
		tableplus = "􀏣",
		videochat = "󰍫",
		daisy_disk = "󰞯",
		screensaver = "󱄄",
		cleanshot_x = "􀎼",
		ledger_live = "􀂪",
		jdownloader = "􁾮",
		["1password"] = "􀢫",
		remote_desktop = "󰢹",
	},
}
